export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  LISTING_NOT_PUBLISHABLE: 'LISTING_NOT_PUBLISHABLE',
  GAME_MARKETPLACE_DISABLED: 'GAME_MARKETPLACE_DISABLED',

  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  NOT_TRANSACTION_PARTICIPANT: 'NOT_TRANSACTION_PARTICIPANT',

  PAYMENT_INIT_FAILED: 'PAYMENT_INIT_FAILED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  DISPUTE_NOT_FOUND: 'DISPUTE_NOT_FOUND',
  DISPUTE_ALREADY_OPEN: 'DISPUTE_ALREADY_OPEN',

  ACCESS_NOT_YET_RELEASABLE: 'ACCESS_NOT_YET_RELEASABLE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
